### ISSUE TITLE
swagger UI always sends JSON

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/cowboy-swagger#24]
Regardless of what I add to the trails metadata for my endpoints, swagger always try to send contents as `application/json`:
![swagger_ui](https://cloud.githubusercontent.com/assets/93657/10483842/dbb91ae0-7257-11e5-92d1-aca262e01fa2.png)

**Comment by harenson** [comment]
@elbrujohalcon If you want to send anything to a given endpoint, you must set `consumes` to  `[""]` \(a list with an empty string\) in the trails metadata for the given endpoint.

Example:

```erlang
, consumes => [""]
```

![screenshot from 2015-11-29 19 27 02](https://cloud.githubusercontent.com/assets/216031/11461331/388cd888-96cf-11e5-8e6d-50136c58e8e8.png)

**Comment by elbrujohalcon** [comment]
Thanks @harenson
