### ISSUE TITLE
basePath should be considered part of the trails path

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/cowboy-swagger#25]
Even when #22 is fixed by just setting `basePath => ""`, sometimes having a `basePath` (e.g. `/admin/api`) is actually useful, but swagger has to consider that such a basePath will be *included* in the trails routes, at least until inaka/cowboy-trails#22 is implemented. And in that case, `basePath` should be taken from there and not as an extra swagger property.

**Comment by Euen** [comment]
![screen shot 2015-12-01 at 12 09 53 pm](https://cloud.githubusercontent.com/assets/1340695/11504553/bb376612-9824-11e5-89ca-c4a4839a29b2.png)

Var baseUrl needs to be updated to change this text field adding the corresponding api_root

e.g. change 

http://localhost:8383/api-docs/swagger.json

to

http://localhost:8383/admin/api/api-docs/swagger.json
