### ISSUE TITLE
Location in response headers is not reading path values

### ISSUE THREAD

**Issue by harenson** [inaka/cowboy-swagger#43]
`location` in `Response Headers` should be: 
"/newspapers/**newspaper1**/news/1b62ce01-59a2-4e70-8388-88d264ae0f72"*
instead of:
 "/newspapers/**:news**/news/1b62ce01-59a2-4e70-8388-88d264ae0f72"*

![screenshot from 2015-12-14 15 52 34](https://cloud.githubusercontent.com/assets/216031/11794108/a5478086-a27d-11e5-8d59-fe38085ed161.png)

**Comment by elbrujohalcon** [comment]
Not a problem with this library
