### ISSUE TITLE
Hello can this project support the cowboy REST part?

### ISSUE THREAD

**Issue by T-tssxuan** [inaka/cowboy-swagger#61]
According what I learned, the cowboy REST are not directly define the HTTP method such as "PUT", "GET", "POST", It uses the methods such as ``` allowed_methods```. I just wander that this app can supports the cowboy REST. 
Thanks a lot.

**Comment by elbrujohalcon** [comment]
@T-tssxuan I think what you're looking for is something like [sumo REST](https://github.com/inaka/sumo_rest).

**Comment by T-tssxuan** [comment]
thanks, a lot.
