### ISSUE TITLE
Definitions description in README

### ISSUE THREAD

**Issue by dzimi** [inaka/cowboy-swagger#73]
Hi !

 When I followed instructions in README  about creating schema then my swagger ui didn't work. It worked when I changed maps keys and values to  binary string. So only the following configuration worked for me:

option 1:

```
`[ ... % other configurations
, { cowboy_swagger
  , [ { global_spec
      , #{ swagger => "2.0"
         , info => #{title => "My app API"}
         , definitions => #{
             <<"RequestBody">> =>
               #{ <<"name">> =>
                   #{ <<"type" => <<"string">>
                    , <<"description">> => <<"Newspaper name">>
                    }
                , <<"description">> =>
                        #{ <<"type" =><< "string">>
                     , <<"description">> => <<"Newspaper description">>
                    }
                }
           }
         }
      }
    ]
  }
]`
```

option2:

```
`-spec trails() -> trails:trails().
trails() ->
  DefinitionName = <<"RequestBody">>,
  DefinitionProperties =
    #{ <<"name">> =>
         #{ <<"type">> => <<"string">>
          , <<"description">> => <<"Newspaper name">>
          }
     , <<"description">> =>
         #{ <<"type">> => <<"string">>
          , <<"description">> => <<"Newspaper description">>
          }
     },
  % Add the definition
  ok = cowboy_swagger:add_definition(DefinitionName, DefinitionProperties),
  ...`
```

Is it a bug in README or maybe something has changed and broke the configuration?

**Comment by harenson** [comment]
Hi @dzimi sorry for the late response.

I think your issue is with the definition name, since it starts with an uppercase letter you need to put that name as a binary value. If this is not the case, please paste the error text so we can get a better idea about the issue :)

You have some typos in `option 1` by the way; you have `<<"type" => <<"string">>` instead of `<<"type">> => <<"string">>`. Do you see the missing `>>`?

**Comment by dzimi** [comment]
Hi @harenson also sory for the late response. I think I had problem with keys such as `type`, `description` etc. which in README examples are atoms. In fact now I cannot reproduce my issue, I change everything to atom and it works. Maybe I used old version? I don't know. So for now I will close this issue. Thanks !
